# Custom Language File for Launcher Customizer

[ejs.app]
title = "The Garden Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/8JEqt22V"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "더 가든에 오신 것을 환영합니다!"
welcomeDescription = "더 가든은 스트리머들을 위한 임시 서버입니다!"
welcomeDescCTA = "아래를 클릭하여 진행하세요!"
